### ISSUE TITLE
ECC Fireside Chat, Oct 10th - Emurgo, Fida Finance

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#103]
**Dear speakers** please go to this link: https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Please take this info (socials, logo, and slides) and post it in the comment section here below. 
(you may need to make a git account) 

----

**Dear team** these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Discord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event one-pager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [x] Tweet & Discord update
- [x] Documentation

**Comment by Claire-ADA** [comment]
Website : https://fida.finance/
Twitter : https://x.com/fida_finance
Discord : https://discord.com/invite/kFdXXBqwdu
Github : https://github.com/fida-services/
Medium : https://medium.com/@fida.finance
Whitepaper : https://docs.fida.finance/
Linktree : https://linktr.ee/fida_finance

**Comment by ubani** [comment]
Discord Event Link: https://discord.gg/27yGxVwS?event=1290645617999089746

Zoom Link: https://us06web.zoom.us/j/86885329886?pwd=K1iHnvEeTm4YNECQszhkqN1jIKQmuM.1

**Comment by Osh-X** [comment]
EMURGO

Website: https://www.emurgo.io/
Twitter/X: https://x.com/emurgo_io
Discord: https://discord.com/invite/AWEp2SG437
YouTube: @EMURGO https://www.youtube.com/channel/UCgFQ0hHuPO1QDcyP6t9KZTQ

**Comment by Osh-X** [comment]
One-Pager:
[EMURGO_ An Introduction.pdf](https://github.com/user-attachments/files/17328038/EMURGO_.An.Introduction.pdf)
Slide 19 please

**Comment by Odiobill** [comment]
Slides: https://pitch.com/v/ecc-fireside-chat-october-10-2024-idz5ii
[ECC Fireside Chat October 10, 2024.pdf](https://github.com/user-attachments/files/17329112/ECC.Fireside.Chat.October.10.2024.pdf)

**Comment by ubani** [comment]
<img width="537" alt="emurgo-fida" src="https://github.com/user-attachments/assets/8e5e4c22-c1ef-4212-97d1-76dde1a79cef">

**Comment by ubani** [comment]
https://youtu.be/xIFSOW2Aw4M

https://x.com/EuCardano/status/1847247037961531592

**Comment by kryptt** [comment]
Website: https://fida.finance/
X: https://x.com/fida_finance
Link Tree: https://linktr.ee/fida_finance
Discord: https://discord.gg/kFdXXBqwdu
Github: https://github.com/fida-services/
Medium: https://medium.com/@fida.finance

Proposals:
Tap into Insurance Policies handled by etherisk: https://cardano.ideascale.com/c/idea/132849/comments/133796
Cyber Security Insurance for the Cardano Community: https://cardano.ideascale.com/c/idea/129014
Life Insurance for the Cardano Citizen: https://cardano.ideascale.com/c/idea/129009
