### ISSUE TITLE
ECC Fireside Chat, Nov 7th - Storm Partners, GenWealth, Larissa.Health

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#105]
**Dear speakers** please go to this link: https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Please take this info (socials, logo, and slides) and post it in the comment section here below. 
(you may need to make a git account) 

----

**Dear team** these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Discord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event one-pager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [ ] Tweet & Discord update
- [x] Documentation

**Comment by Rafael-C-H** [comment]
GenWealth

Website: https://genwealth.app/
Twitter/X: https://x.com/genwealth_app
Discord: https://discord.gg/EXZKzAwn3a
YouTube: https://www.youtube.com/@decentralizednation
GitHub: https://github.com/gen-wealth


![GenWealth high resolution 2](https://github.com/user-attachments/assets/71328312-025c-4b27-bde4-436243e57bd1)

![GenWealth Slide 1 European Townhall](https://github.com/user-attachments/assets/99496401-ef92-444d-81f9-c74972e9ca01)

**Comment by ubani** [comment]
**Larissa.Health** 




Website:   https://larissa.health
Twitter/X:  https://x.com/larissa_health
Twitter/X:  https://x.com/birth_stakepool
Discord:    https://discord.gg/EXZKzAwn3a
YouTube:   https://www.youtube.com/@larissa.health




![Image](https://github.com/user-attachments/assets/2397d608-68a2-4cae-a280-34633e584cf2)



![Image](https://github.com/user-attachments/assets/b3258ff6-aabb-4a7e-9dda-f50a575c6e8c)

**Comment by ubani** [comment]
https://x.com/EuCardano/status/1853868734173094250

https://discord.gg/EMCCaCAV?event=1296486827741548645

**Comment by FiveFoldU** [comment]
STORM Partners
Website: https://storm.partners/
Twitter/X: https://x.com/storm_partners
Telegram: @STORMPartners
YouTube: https://www.youtube.com/@DecentralHouse
![01_Storm_Logo_original_black (1)](https://github.com/user-attachments/assets/202254fc-1396-43ad-87a8-10e88ceea6cb)

**Comment by FiveFoldU** [comment]
Here are STORM Partner's 2 Partner Proposals:

Wachsman Partnership PR + Accelerator:
https://cardano.ideascale.com/c/cardano/idea/134690

UNITAR partnership for UN adoption:
https://cardano.ideascale.com/c/cardano/idea/134672

**Comment by ubani** [comment]
![Image](https://github.com/user-attachments/assets/1fc6a49d-ffe8-4b96-9b2b-88ff6c693182)

**Comment by ubani** [comment]
DaoCounting Proposal: https://cardano.ideascale.com/c/cardano/idea/130573
