### ISSUE TITLE
ECC Fireside Chat, Dec 5th Landano, NESSO, Iagon

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#106]
**Dear speakers** please go to this link: https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Please take this info (socials, logo, and slides) and post it in the comment section here below. 
(you may need to make a git account) 

----

**Dear team** these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Discord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event one-pager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [x] Tweet & Discord update
- [ ] Documentation

**Comment by aaronmoguin** [comment]
Hi this is Aaron Moguin, COO of Landano, you can call me Aaron.
Here are our logo and banner slide, to the dimensions you requested:
![2412 banner slide](https://github.com/user-attachments/assets/72b39448-6733-48a7-a788-8c28755f9d5f)
![landano io-logo-550x100px](https://github.com/user-attachments/assets/d2a5f642-ba83-4705-9468-7dd55040aefb)
socials:
Website: https://www.landano.io/
Twitter/X: https://x.com/landanodapp
Discord: https://discord.gg/tbT92r3x
YouTube: https://youtube.com/@
Telegram: @amoguin 
GitHub: https://github.com/landano
joining discord as we speak :) see you all thursday!

**Comment by ubani** [comment]
![Uploading landano-iagon-nesso.png…]()

**Comment by aaronmoguin** [comment]
new landano white logo as requested: 
![landano io-logo-550x100px white](https://github.com/user-attachments/assets/ce4e08ec-d583-4389-9e28-610ab11cce4d)

**Comment by pavobabenkoua** [comment]
Speaker
**Navjit Dhaliwal, CEO at Iagon**

Logo 
![iagon-logo](https://github.com/user-attachments/assets/4922a7d3-7763-4ec6-9be4-f7e662353224)

Onepager
![EUcardano-slide](https://github.com/user-attachments/assets/a0f3adfd-63a1-4e40-b7bc-1fbf61ada648)


Social Links
**Iagon** 
Website: https://iagon.com/
Twitter/X: https://x.com/IagonOfficial
Discord: https://discord.gg/TCS23VWuWm
YouTube: https://www.youtube.com/channel/UCpIUqQSMK5cE4QncanEUpKg
Telegram: https://t.me/+EV3SS33aPUUzYWNi
GitHub: https://github.com/Iagonorg

**Comment by Lorenzonesso** [comment]
![Nesso_wordmark_blue](https://github.com/user-attachments/assets/d42cf675-e46f-4676-9511-ae810299d189)
![Nesso_icon_blue](https://github.com/user-attachments/assets/7b4e8210-b9d2-4986-9092-a80afe3b7212)
![Ne
![Nesso_white](https://github.com/user-attachments/assets/b352e90a-9b84-40be-8af1-a273fcdac444)
sso_wordmark_white](https://github.com/user-attachments/assets/23e5ff41-cd26-46b0-9668-ddbb0e759c60)


![IMG_2551](https://github.com/user-attachments/assets/5041e4f2-e1d9-4099-9e0d-914406f1e833)

LINKS:
X: https://x.com/nesso
Website: https://nesso.agency
Book a Call: https://calendly.com/nessoagency

Speaker:

Lorenzo Martani, founder of NESSO (https://x.com/lorenzonesso)

**Comment by Odiobill** [comment]
Slides for the event: https://pitch.com/v/ecc-fireside-chat-december-5-2024-69hqq4

[ECC Fireside Chat December 5, 2024.pdf](https://github.com/user-attachments/files/18025396/ECC.Fireside.Chat.December.5.2024.pdf)

**Comment by ubani** [comment]
![Uploading landano-iagon-nesso.png…]()

**Comment by ubani** [comment]
https://youtu.be/VocdUTTWEsc

https://x.com/EuCardano/status/1865767853909062102
