### ISSUE TITLE
F10 Final Report: Closing Report

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#18]

**Comment by thegrizzly1** [comment]
Dear all, the closing report is now ready for submission via the Milestone Module.

https://european-cardano-community.gitbook.io/core-team-area-european-cardano-community/cardano-catalyst-fund/fund-10/closing-report-fund-10-scope

Please - could you read through it, and comment or propose any chances you consider necessary?
Please focus mainly on the closing words, and the comments regarding further utilisation of the remaining funds.
