### ISSUE TITLE
ECC: Fireside Chat: MELD, Adam K. Dean, WildTangz, Feb14th 2024

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#20]
https://zoom.us/meeting/register/tJUlcO2urDIsGtW-tNJtRYkhifo12e1RO_eR
- MELD
- Adam K Dean
- WildTangz

**Comment by ubani** [comment]
- [ ] Discord Event
- [ ] Banner
- [ ] Tweet 72 hours in advance
- [ ] Tweet 24 hours in advance
- [ ] Tweet 60 Minutes in advance
- [ ] Edit Video
- [ ] Upload & Description
- [ ] Timestamp
- [ ] Tweet & Discord update
- [ ] Documentation

**Comment by ubani** [comment]
Event Banner 

<img width="540" alt="meld-adamkdean-wildtangz" src="https://github.com/eucardano/operations-framework/assets/7843228/7bdb510b-a0be-43b2-b27e-1c18a1aa74f3">

**Comment by ubani** [comment]
Event Banner 

<img width="540" alt="meld-adamkdean-wildtangz" src="https://github.com/eucardano/operations-framework/assets/7843228/7bdb510b-a0be-43b2-b27e-1c18a1aa74f3">

**Comment by ubani** [comment]
**Socials **

```
**MELD**


**Adam Dean**
CIP Editor & Cardano Community Member
Twitter/X: https://twitter.com/adamKDean
Discord: therealadamdean


**Wild Tangz**
Website: https://wildtangz.com/
Twitter/X: https://twitter.com/wildtangz
Discord: discord.gg/wildtangz
YouTube: https://youtube.com/@wildtangz
GitHub: https://github.com/thaddeusdiamond
```

**Comment by ubani** [comment]
Tweet https://twitter.com/EuCardano/status/1757081841524175302

**Comment by Crypto2099** [comment]
Adam Dean one-pager?

![CIPs OnePager](https://github.com/eucardano/operations-framework/assets/63186174/ae90b2c5-666f-4064-8edf-6dd0e4eba1ed)

**Comment by ubani** [comment]
MELD one-pager

![Meld](https://github.com/eucardano/operations-framework/assets/7843228/f64b400b-5f9e-4419-a22a-4460988f33c1)

**Comment by Odiobill** [comment]
Slides for the meeting:
[ECC Fireside Chat Feb 15th 2024.pdf](https://github.com/eucardano/operations-framework/files/14299938/ECC.Fireside.Chat.Feb.15th.2024.pdf)

**Comment by ubani** [comment]
https://youtu.be/0uLDWXsYolU

https://twitter.com/EuCardano/status/1758454837644042362

**Comment by ubani** [comment]
@Odiobill ready to timestamp
