### ISSUE TITLE
ECC Fireside Chat: Fluid Tokens, SoundRig, Adakonda Feb, 29th - 18:30 CET

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#24]
Link to event: https://zoom.us/meeting/register/tJUlcO2urDIsGtW-tNJtRYkhifo12e1RO_eR

**Use this guide as Template** https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

- Fluid Tokens
- SoundRig
- Adakonda

- [x] Discord Event
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/socials.md)
- [x] Remember projects regarding Event onepager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [x] Tweet & Discord update
- [x] Documentation

**Comment by Odiobill** [comment]
Adakonda Logo
![logo_800x800](https://github.com/eucardano/operations-framework/assets/1734694/de37ce5f-5829-429c-9eed-da192cc1b422)

**Comment by Odiobill** [comment]
Fluid Tokens logo(s)
![fluid](https://github.com/eucardano/operations-framework/assets/1734694/e2340e83-b9e3-42bb-93de-8baff17e1901)
![fluid-1](https://github.com/eucardano/operations-framework/assets/1734694/107329b4-991e-45b8-a404-505a10a65250)

**Comment by Odiobill** [comment]
![image](https://github.com/eucardano/operations-framework/assets/1734694/6406c762-74e2-4bce-b0fc-9ae7ff0c0dbb)

**Comment by SunnySoundRig** [comment]
![Coloured transparent](https://github.com/eucardano/operations-framework/assets/161717378/c10e93cf-eb94-4137-bed4-66fa3858d06d)

**Comment by SunnySoundRig** [comment]
![Project SIMBA Day   Night logos (Twitter Post) (1)](https://github.com/eucardano/operations-framework/assets/161717378/c76919e6-c6bc-4395-9bea-9e1c5558023d)

**Comment by SunnySoundRig** [comment]
[SIMBA Alliances.pdf](https://github.com/eucardano/operations-framework/files/14447624/SIMBA.Alliances.pdf)

**Comment by Odiobill** [comment]
[ECC Fireside Chat Feb 29th 2024.pdf](https://github.com/eucardano/operations-framework/files/14447783/ECC.Fireside.Chat.Feb.29th.2024.pdf)

**Comment by SunnySoundRig** [comment]
[SIMBA Alliances.pdf](https://github.com/eucardano/operations-framework/files/14451304/SIMBA.Alliances.pdf)

**Comment by Odiobill** [comment]
@FluidTokens 
http://fluidtokens.com
https://discord.com/invite/nNmBhMUGtj
No youtube, no telegram 
https://github.com/FluidTokens


$KONDA (AdaKonda)
Website: https://konda.app
Twitter: https://x.com/adakondacoin
Discord: https://discord.gg/H4avQaqzfV
Telegram: https://t.me/+tY3gNZJg8eU1ZGZi

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/e4af3c71-54bc-42d7-a86e-916f9c5c3490)

**Comment by ubani** [comment]
https://youtu.be/sCxZXrvmeT8
