### ISSUE TITLE
Fireside Chat, March 14th - VyFinance TxPipe with GitHoney, Decentralized Redis 

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#29]
Dear speakers please **Use this guide as template** to post your socials and slides as an answer of this GitHub issue:   https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Dear team these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Discord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event onepager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [x] Tweet & Discord update
- [ ] Documentation

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/64ccbb9d-5b8d-425a-bc71-efb94cfc44c3)

**Comment by ubani** [comment]
# Discord Event link

https://zoom.us/meeting/register/tJUlcO2urDIsGtW-tNJtRYkhifo12e1RO_eR

**Comment by ubani** [comment]
Tweet https://twitter.com/EuCardano/status/1767221395216306347/photo/1

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/79658834-4303-42c6-ae1f-3519e88f8bde)
![Image](https://github.com/eucardano/operations-framework/assets/7843228/225ad111-9e10-43f4-ae72-c26ed1cfa5c6)
![Image](https://github.com/eucardano/operations-framework/assets/7843228/90b3f542-5bcf-415c-b568-242604551028)

**Comment by scarmuega** [comment]
TxPipe

Website: https://txpipe.io
Twitter/X: https://x.com/txpipe_tools
GitHub: https://github.com/txpipe


![Image](https://github.com/eucardano/operations-framework/assets/653886/da0f2811-11b8-4bec-a546-b83061cd153d)

**Comment by Odiobill** [comment]
[ECC Fireside Chat March 14th 2024.pdf](https://github.com/eucardano/operations-framework/files/14603688/ECC.Fireside.Chat.March.14th.2024.pdf)

**Comment by Odiobill** [comment]
[ECC Fireside Chat March 14th 2024 (1).pdf](https://github.com/eucardano/operations-framework/files/14605140/ECC.Fireside.Chat.March.14th.2024.1.pdf)

**Comment by Odiobill** [comment]
[ECC Fireside Chat March 14th 2024 (2).pdf](https://github.com/eucardano/operations-framework/files/14605963/ECC.Fireside.Chat.March.14th.2024.2.pdf)

**Comment by PedroLucasnet** [comment]
45B - Cardano Enablement
* https://45b.io | hello@45b.io
* Follow our X [@45B_Cardano](https://twitter.com/45B_Cardano)
* Join [45B's Discord](https://discord.gg/nXZJ24qaRZ) to discuss
* Instagram:
  * English [@45b_io](https://www.instagram.com/45b_io)
  * Portuguese [@45b.pt](https://www.instagram.com/45b.pt)
* Cardano for non-techs [Linktree](https://linktr.ee/cardanofornontechs) | [Whatsapp](https://chat.whatsapp.com/GnhFsjDSY5SAXkvzfNHkzN)


![Image](https://github.com/eucardano/operations-framework/assets/3915618/e39d7f65-ef75-4c6c-ad30-4b35ccad2b13)

**Comment by ubani** [comment]
We unfortunately had two no-shows. That where greatly and spontaneously filled by two community members.  
Thus it feels appropriate to adapt the slides.

<img width="540" alt="txpipe-DLT360-45B" src="https://github.com/eucardano/operations-framework/assets/7843228/592cf9db-5689-4db8-bc6e-8b194230f529">

**Comment by ubani** [comment]
https://youtu.be/KjON5IkPNoE
