### ISSUE TITLE
Fireside Chat, March 28th: Ada Exchange, Ada Pulse, Cryptofluency.io, VyFinance

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#30]
Dear speakers please **Use this guide as template** to post your socials and slides as an answer of this GitHub issue:   https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Dear team these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Dicord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event onepager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [ ] Upload & Description
- [ ] Timestamp
- [ ] Tweet & Discord update
- [ ] Documentation

**Comment by ubani** [comment]
- [ ] Cardano Thor
- [ ] Ada Exchange

**Comment by cryptofluency** [comment]
Cryptofluency.io
Derek Hopkins, Founder, Cryptofluency LLC

Website: https://cryptofluency.io
Twitter/X: https://x.com/cryptofluencyio
YouTube: https://youtube.com/@cryptofluencyio


![Image](https://github.com/eucardano/operations-framework/assets/165054215/212046ca-dc53-4406-95b0-0e30742b1038)

**Comment by cryptofluency** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/165054215/175fc2fc-dd65-4627-87cd-00beefbf5385)

**Comment by cryptofluency** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/165054215/64130331-3dce-44c2-92de-4636d19d7a82)

**Comment by Odiobill** [comment]
[ECC Fireside Chat March 28th 2024.pdf](https://github.com/eucardano/operations-framework/files/14788919/ECC.Fireside.Chat.March.28th.2024.pdf)

**Comment by Odiobill** [comment]
https://pitch.com/v/ecc-fireside-chat-march-28th-2024-wu22xz

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/1b7a49a0-3e97-43ec-80b9-15a6e12abae8)

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/909be2cd-2008-4660-b43c-6a90a2563016)

**Comment by ubani** [comment]
https://twitter.com/EuCardano/status/1774487775212945643

https://youtu.be/haSlYRHsp3Y

**Comment by ubani** [comment]
I created two Product Demos, as the space went longer than expected

https://twitter.com/EuCardano/status/1774492766485073939

https://twitter.com/EuCardano/status/1774492847783215443

**Comment by Odiobill** [comment]
VyFi

Discord: https://discord.com/invite/ed4SeUzmmW
X: https://twitter.com/VyFiOfficial
App/Website: https://app.vyfi.io/
