### ISSUE TITLE
Fireside Chat, April 11th: Cardano Thor, Arbiter, Mynth

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#31]
Dear speakers please **Use this guide as template** to post your socials and slides as an answer of this GitHub issue:   https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Dear team these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Dicord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/socials.md)
- [x] Remember projects regarding Event onepager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [x] Tweet & Discord update
- [x] Documentation

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/c7cdf665-8cf5-4e6b-9663-515b6d887080)

**Comment by ubani** [comment]
https://twitter.com/EuCardano/status/1777380165984592228

https://discord.com/events/994521479016357898/1222358351199993989

**Comment by Odiobill** [comment]
**ARBITER**

Website: https://automatictradingsolution.com/)
Twitter/X: https://twitter.com/ARBITERxyz
Discord: https://discord.gg/mEfXtsVbmF


Logo: 
![Image](https://github.com/eucardano/operations-framework/assets/1734694/599b2ab7-ef63-430b-b994-5e016d98fb45)


Onepager:
![Image](https://github.com/eucardano/operations-framework/assets/1734694/663e8b9f-33a2-4481-8336-bcfdb747afbe)

**Comment by SynthLuvr** [comment]
**Mynth**

Website: https://mynth.ai/
Twitter/X: https://twitter.com/_mynth_
Discord: https://mynth.ai/discord

Logo:
![Image](https://github.com/eucardano/operations-framework/assets/131367121/9825de12-67de-4c65-89fc-51a6e0997e0b)

Onepager:
![Image](https://github.com/eucardano/operations-framework/assets/131367121/f6b0c266-4226-48a7-9d5b-43475a7379e9)

**Comment by ubani** [comment]
From last FS.

**Revuto**
Website: https://revuto.com, and https://crypto.revuto.com
Twitter/X: https://twitter.com/get_revuto
Discord: https://discord.gg/RTNnnmt4xU
YouTube: https://www.youtube.com/@RevutoOfficialChannel
Telegram: https://t.me/getrevuto

![Image](https://github.com/eucardano/operations-framework/assets/7843228/4620a909-7134-4948-8ea2-2f899653c67d)

**Comment by Odiobill** [comment]
https://pitch.com/v/ecc-fireside-chat-april-11th-2024-sj5qhv



[ECC Fireside Chat April 11th 2024.pdf](https://github.com/eucardano/operations-framework/files/14947141/ECC.Fireside.Chat.April.11th.2024.pdf)

**Comment by Odiobill** [comment]
[ECC Fireside Chat April 11th 2024 (1).pdf](https://github.com/eucardano/operations-framework/files/14948131/ECC.Fireside.Chat.April.11th.2024.1.pdf)

Updated version with Revuto

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/caddf540-4667-41d0-8943-f72cfa25287c)

**Comment by ubani** [comment]
https://youtu.be/vquo-v4mSDQ
