### ISSUE TITLE
Fireside Chat, May 23rd Trust over IP, IamX, Hyperledger Identus

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#34]
**Dear speakers** please go to this link: https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Please take this info (socials, logo, and slides) and post it in the comment section here below. 
(you may need to make a git account) 

----

**Dear team** these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Discord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event one-pager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [x] Tweet & Discord update
- [ ] Documentation

**Comment by ubani** [comment]
Discord Event link: https://discord.gg/RfUC7P5C?event=1229753395775279115

Zoom Registration: https://zoom.us/meeting/register/tJUlcO2urDIsGtW-tNJtRYkhifo12e1RO_eR

**Comment by FayyaadhAdams** [comment]
**Speaker**: Fayyaadh but you can call me Fay

**Logo**: 

![Image](https://github.com/eucardano/operations-framework/assets/118432384/10efdd7c-acad-437c-b92c-7c1e18ea0b8a)

**One pager**


[EU Fireside Chat.pdf](https://github.com/eucardano/operations-framework/files/15388738/EU.Fireside.Chat.pdf)

**Socials**:

Hyperledger Identus

Twitter: NA
Discord Atala: https://discord.gg/QNxeWkJr
Discord Hyperledger: https://discord.gg/hyperledger
Youtube: https://www.youtube.com/@Hyperledger/videos
Github: https://github.com/hyperledger/identus-cloud-agent

**Comment by Odiobill** [comment]
Slides for the event:



[ECC Fireside Chat May 23, 2024.pdf](https://github.com/eucardano/operations-framework/files/15419362/ECC.Fireside.Chat.May.23.2024.pdf)



https://pitch.com/v/ecc-fireside-chat-may-23-2024-3mkicr

**Comment by Odiobill** [comment]
Links shared during the event:

_Trust over IP + Hyperledger_
- https://wiki.trustoverip.org/display/HOME/Trust+Registry+Task+Force
- https://trustoverip.github.io/tswg-trust-registry-protocol/
- https://trustoverip.org/toip-model/
- https://discord.gg/atala

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/501db062-d0d6-4fc1-a1fc-7eeb512eab19)

**Comment by ubani** [comment]
https://youtu.be/X3EC0_P_mV4
