### ISSUE TITLE
Fireside Chat, June 6th - AdaAxolotl, M2tech, Harmonic Labs

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#35]
**Dear speakers** please go to this link: https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Please take this info (socials, logo, and slides) and post it in the comment section here below. 
(you may need to make a git account) 

----

**Dear team** these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Dicord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event one-pager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [ ] Tweet & Discord update
- [ ] Documentation

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/31172f3b-a1fa-47d1-8214-4b3ca0d4165f)
![Image](https://github.com/eucardano/operations-framework/assets/7843228/5d8fed05-efa7-4a76-b598-b467934e4ce8)
![Image](https://github.com/eucardano/operations-framework/assets/7843228/76bd7c05-a2bd-47dc-b6e3-1fc76c992b2a)

**Comment by ubani** [comment]
![Image](https://github.com/eucardano/operations-framework/assets/7843228/416c8181-cb76-4116-8302-f11a3971b125)

**Comment by ubani** [comment]
https://x.com/EuCardano/status/1797580979642523693

2/n

Join us Discord: [https://discord.gg/nSnPMNwxrJ](https://t.co/yMW8iFTiMt)

Discord Event link: [https://discord.gg/tTU3ag5v?event=1247120769717243915](https://discord.gg/tTU3ag5v?event=1247120769717243915)

Zoom Registration: [https://zoom.us/meeting/register/tJUlcO2urDIsGtW-tNJtRYkhifo12e1RO_eR](https://t.co/clCYPs8ujK)

**Comment by ADAAxolotl** [comment]
Project:  ADA Axolotl

Website: https://www.AdaAxolotl.com/org
Twitter: https://x.com/AdaAxolotl.com/
Discord: https://discord.gg/vSmD7McQNc
YouTube: https://www.youtube.com/channel/UCy62FpxDZGwltgh6V7hfwWA
Telegram: NA
GitHub: ****


![Image](https://github.com/eucardano/operations-framework/assets/171742597/0edcee70-55e0-4516-91d8-d2cbe61e6fa3)

**Comment by Odiobill** [comment]
Link to the slides: https://pitch.com/v/ecc-fireside-chat-june-6-2024-p52b6d



[ECC Fireside Chat June 6, 2024.pdf](https://github.com/user-attachments/files/15635331/ECC.Fireside.Chat.June.6.2024.pdf)

**Comment by ubani** [comment]
https://youtu.be/TBeOxbowZLo
