### ISSUE TITLE
Fireside Chat, Aug 1st - NFT Auth Framework, Digital Gold Ecosystem, KeyStone Wallet

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#39]
**Dear speakers** please go to this link: https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Please take this info (socials, logo, and slides) and post it in the comment section here below. 
(you may need to make a git account) 

----

**Dear team** these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Dicord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event one-pager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [ ] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [x] Tweet & Discord update
- [x] Documentation

**Comment by DigitalGold2022** [comment]
Digital Gold Ecosystem

Website: https://www.digitalgoldecosystem.com/
Twitter/X: https://x.com/DigitalGold2022
Discord:https://discord.gg/7TyRB738vJ
YouTube: https://www.youtube.com/channel/UCVnJXnM8DhxL8VpyxmzK-cw
Telegram:None
GitHub: https://github.com/DigitalGold2022)))

![Logo Banner 515x110](https://github.com/user-attachments/assets/5b3ecf62-f061-46d4-87e0-6f52b07322cd)

**Comment by DigitalGold2022** [comment]
Still working on the presentation.  Will upload asap.  TY

**Comment by ubani** [comment]
Discord Event Link: https://discord.gg/3xrezF7UQ5?event=1259879460052795412
Zoom: https://us06web.zoom.us/meeting/register/tZ0vcOmvrTgrHdCNi3AMKn-bnSroZV50eDCE

**Comment by ckaraca** [comment]
Website: https://https://www.littlefish.foundation/
Twitter/X: https://x.com/littlefishDAO
Discord: https://discord.gg/d3ufMDR5jU
YouTube: https://www.youtube.com/@littlefishFoundation
GitHub: https://github.com/littlefish-foundation
![logo1](https://github.com/user-attachments/assets/5b48e6d1-1910-4474-b0cd-22b4279b9363)
![logo1d](https://github.com/user-attachments/assets/7b3a0ee1-c0ca-4536-a768-befafcffe711)

**Comment by Leray1206** [comment]
![How to Safeguard Your Crypto Assets (1)](https://github.com/user-attachments/assets/ef2c7c2a-d282-4fd0-b3a9-5afb4e66ca59)

Keystone Hardware Wallet

Speaker: Keystone CEO -- Lixin Liu

Website: https://keyst.one/
Twitter/X: https://x.com/@keystonewallet
Discord: https://discord.com/invite/6vEfPEJKJD
YouTube: https://youtube.com/@KeystoneWallet
Telegram: https://t.me/KeystoneWallet
GitHub: https://github.com/KeystoneHQ/keystone3-firmware

**Comment by ubani** [comment]
![Image](https://github.com/user-attachments/assets/8ab20ada-3e7f-435f-a665-a5955b4d6e6e)



https://discord.com/events/994521479016357898/1259879460052795412

**Comment by Odiobill** [comment]
https://pitch.com/v/ecc-fireside-chat-august-1-2024-r48wrp

[ECC Fireside Chat August 1, 2024.pdf](https://github.com/user-attachments/files/16456133/ECC.Fireside.Chat.August.1.2024.pdf)
