### ISSUE TITLE
Fireside Chat, Aug 15th, Tempo Vote, LidoNation, Mateusz / $matiwinnetou

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#40]
**Dear speakers** please go to this link: https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Please take this info (socials, logo, and slides) and post it in the comment section here below. 
(you may need to make a git account) 

----

**Dear team** these are our tasks as usual  

- [x] Add projects to title
- [x] Discord Event
- [x] Add Dicord event link in answers
- [x] Banner
- [x] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [x] Remember projects regarding Event one-pager
- [x] Tweet 72 hours in advance
- [x] Tweet 24 hours in advance
- [x] Event Slides
- [x] Tweet 60 Minutes in advance
- [x] Edit Video
- [x] Upload & Description
- [ ] Timestamp
- [x] Tweet & Discord update
- [x] Documentation

**Comment by ubani** [comment]
Discord Event Link: https://discord.gg/3xrezF7UQ5?event=1265351182885584979
Zoom: https://us06web.zoom.us/meeting/register/tZ0vcOmvrTgrHdCNi3AMKn-bnSroZV50eDCE

**Comment by thuchintran** [comment]
Tempo
Website: https://tempo.vote/
Twitter: https://x.com/tempo_vote
Telegram: https://t.me/+cRYzgxwFDAJkZjdl
Logo: 
![Tempo-logo](https://github.com/user-attachments/assets/2091d3a9-281a-48d1-a978-fe05caa873dd)
Slide: will update soon

**Comment by thuchintran** [comment]
Slide onepage: 
![Onepage-Tempo](https://github.com/user-attachments/assets/6b22eaea-532e-4678-8c93-49fe3a2af0cb)

**Comment by thuchintran** [comment]
![Onepage-Tempo](https://github.com/user-attachments/assets/cff820d9-3ca4-479d-a705-9723214d9472)

**Comment by thuchintran** [comment]
![Onepage-Tempo](https://github.com/user-attachments/assets/95529c15-cc21-4324-ac75-6f7fdd302204)

**Comment by profd2004** [comment]
Website: https://preview.1694.io
Twitter/X: https://x.com/lidonation
Discord: @lidonation
YouTube: https://youtube.com/@lidonation
Telegram: @lidonation
Logo: https://www.lidonation.com/img/llogo-transparent.png

Slide: 
![Image](https://github.com/user-attachments/assets/42272cde-fd16-4868-9f98-f8d1647e8dcf)

**Comment by Odiobill** [comment]
Slides: https://pitch.com/v/ecc-fireside-chat-august-15-2024-vhctbw



[ECC Fireside Chat August 15, 2024.pdf](https://github.com/user-attachments/files/16625279/ECC.Fireside.Chat.August.15.2024.pdf)

**Comment by ubani** [comment]
![Uploading Tempo Vote Lidonation $matiwinnetou.png…]()

**Comment by ubani** [comment]
<img width="537" alt="Tempo Vote Lidonation $matiwinnetou" src="https://github.com/user-attachments/assets/c2fe256d-1db9-4f94-b9bd-92c788651a86">
