### ISSUE TITLE
ECC Fireside Chat, Sept 27th

### ISSUE THREAD

**Issue by ubani** [eucardano/operations-framework#99]
**Dear speakers** please go to this link: https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md

Please take this info (socials, logo, and slides) and post it in the comment section here below. 
(you may need to make a git account) 

----

**Dear team** these are our tasks as usual  

- [ ] Add projects to title
- [ ] Discord Event
- [ ] Add Dicord event link in answers
- [ ] Banner
- [ ] ask projects for current socials [here is the template ](https://github.com/eucardano/brandassets/blob/main/templates/yt-description-socials.md)
- [ ] Remember projects regarding Event one-pager
- [ ] Tweet 72 hours in advance
- [ ] Tweet 24 hours in advance
- [ ] Event Slides
- [ ] Tweet 60 Minutes in advance
- [ ] Edit Video
- [ ] Upload & Description
- [ ] Timestamp
- [ ] Tweet & Discord update
- [ ] Documentation

**Comment by FiveFoldU** [comment]
D.J. (Bodden)

STORM Partners (Switzerland) 

![Image](https://github.com/user-attachments/assets/6820370a-3cab-4ea1-8bfa-97208c654451)
[One slide for Cardano EU _ STORM Partners.pptx.pdf](https://github.com/user-attachments/files/17097638/One.slide.for.Cardano.EU._.STORM.Partners.pptx.pdf)
[One slide for Cardano EU _ STORM Partners.pptx](https://github.com/user-attachments/files/17097645/One.slide.for.Cardano.EU._.STORM.Partners.pptx)

Website: https://storm.partners
LinkedIn: https://ch.linkedin.com/company/stormpartners
Twitter/X: https://twitter.com/STORM_Partners
YouTube: https://www.youtube.com/@DecentralHouse
Luma: https://lu.ma/decentralhouse

Hi folks! I'm D.J., I work in a Web3 management and strategy consulting firm called STORM Partners and we're an ecosystem partner of the Cardano network. We currently have nine proposals in progress and are looking at what is most useful to submit in Fund 13. I flew attack helicopters, I've been a corporate technology buyer, I've sold SaaS to those same corporates, I'm a startup strategy and operations specialist, and I've published over 15 books, many of which explain tech to non-tech people. Ask me anything.

**Comment by ubani** [comment]
Sorry @FiveFoldU , we totally missed this. Please check also your DMs in Discord.
Do you want to join this Thursday? https://github.com/eucardano/operations-framework/issues/103

**Comment by ubani** [comment]
Team couldn't join for personal reasons.
